name: Build and Push to Development

on:
  push:
    branches:
      - master

env:
  PROJECT_ID: dev-buildly
  REGION: us
  IMAGE_NAME: ${{ vars.DEV_DOCKER_IMAGE }}

jobs:
  build:
    name: Build and Push to GCR
    runs-on: ubuntu-latest
    steps:
    - name: "Checkout"
      uses: actions/checkout@v3

    - id: "auth"
      uses: "google-github-actions/auth@v1"
      with:
        credentials_json: "${{ secrets.GCR_JSON_KEY }}"

    - name: "Set up Cloud SDK"
      uses: "google-github-actions/setup-gcloud@v1"

    - name: "Use gcloud CLI"
      run: "gcloud info"

    - name: "Docker auth"
      run: |-
        gcloud auth configure-docker ${{ env.REGION }}-docker.pkg.dev --quiet

    - name: Build docker image
      run: docker build -t $IMAGE_NAME:latest .

    - name: Push to Google Artifact Registry
      run: docker push $IMAGE_NAME:latest

